### PR TITLE
added logic to interpret sequence timestamps and exposed x position

### PR DESCRIPTION
**Pull request by jsatgit**

### CODE REVIEW

**Review by lazukr — APPROVED** [review]
looks good

**Review by lazukr — CHANGES_REQUESTED** [review]
Shouldn't nodejs be part of the dependencies? Or are we expecting them to install npm through nodejs and thus not mentioning it?

**Comment by jsatgit** [comment]
@lazukr: it's implicit. Ill just include a link for clarity

**Review by lazukr — APPROVED** [review]
I suppose this is more clear. If they have any issues with installation, perhaps they'll end up clicking the link and see it.

**Review by lazukr — APPROVED** [review]

**Review by lazukr — APPROVED** [review]

**Review by lazukr — APPROVED** [review]

**Pull request merged**
